### ISSUE TITLE
Set different rules for different workflows

### ISSUE THREAD

**Issue by JohnyP36** [MajorScruffy/delete-old-workflow-runs#2]
How can I apply different settings for each workflow I have? 

So, I have 4 workflows. 
I want workflow 1 to be deleted after 14 days and keep a minimum of 7;
I want workflow 2 to be deleted after 63 days and keep a minimum of 75; 
etc...

How can I manage this in one file? Or do I need 4 workflows to deleted the other 4 workflows?

**Comment by stefan-stanescu-maersk** [comment]
Hi Johny

You should be able to do it in one workflow. Just call the action multiple times.

```
steps:
  - name: Delete workflow runs 1
    uses: MajorScruffy/delete-workflow-runs
    id: delete-workflow-runs-1
    with:
      repository: MajorScruffy/delete-workflow-runs   # replace this with your own repository
      workflow: .github/workflows/workflow1.yml  # replace this with the path to your first workflow
      older-than-seconds: 1209600
      maximum-workflow-runs-to-keep: 7
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  - name: Delete workflow runs 2
    uses: MajorScruffy/delete-workflow-runs
    id: delete-workflow-runs-2
    with:
      repository: MajorScruffy/delete-workflow-runs   # replace this with your own repository
      workflow: .github/workflows/workflow2.yml  # replace this with the path to your second workflow
      older-than-seconds: 5443200
      maximum-workflow-runs-to-keep: 75
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
