### ISSUE TITLE
Not finding workflows to delete

### ISSUE THREAD

**Issue by qd-danh** [MajorScruffy/delete-old-workflow-runs#3]
Hello - really appreciate your custom action, just can't seem to get it to work. 
Have tried both `older-than-seconds` (~1 month), and `created-before` (2022-01-01) options, so far with `what-if` set to true (want to make sure I have parameters correct before letting this thing loose)

and I definitely have older workflow runs (see screenshot)

Really two issues:
- not seeing any workflows listed that are found to delete
- seeing the warning about "Buffer() is deprecated" and not sure if that's related.
 
![2022-03-23 09_00_18](https://user-images.githubusercontent.com/85181651/159764554-3a43e24e-28fb-4e76-818f-382255684445.png)

![2022-03-23 09_02_59](https://user-images.githubusercontent.com/85181651/159764878-660c9a2f-1013-4dab-9bf9-f560c16587d1.png)

```yaml
  - name: Delete old workflow runs
    uses: MajorScruffy/delete-old-workflow-runs@v0.1.0
    with:
      repository: (***redacted***)
      workflow: ".github/workflows/commands.yml"
      # created-before: ${{ github.event.inputs.createdBeforeDate }}
      older-than-seconds: 2592000  # one month
      # created-before: "2021-12-08T16:34:00Z"
      # actor: test@test.com
      # branch: main
      # event: push
      # event: completed
      # maximum-workflow-runs-to-keep: 0
      what-if: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
```
